version: '3.4'
services:
  ###    MongoDb   ####
  mongo:
    image: mongo
    ports:
      - 27017:27017

  ###    Mongo Express   ####
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
