version: '3.4'
services:
  ###    MongoDb   ####
  mongo:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
  #      ME_CONFIG_BASICAUTH_USERNAME: guest
  #      ME_CONFIG_BASICAUTH_PASSWORD: guest
